apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: civicpulse-backend
    newName: ghcr.io/replace-me/civicpulse-backend
    newTag: replace-with-git-sha
  - name: civicpulse-frontend
    newName: ghcr.io/replace-me/civicpulse-frontend
    newTag: replace-with-git-sha
patches:
  - target:
      kind: ConfigMap
      name: civicpulse-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: production
