apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: civicpulse-backend
    newName: civicpulse-backend
    newTag: local
  - name: civicpulse-frontend
    newName: civicpulse-frontend
    newTag: local
patches:
  - target:
      kind: ConfigMap
      name: civicpulse-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: development
